// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entity "github.com/deividhf/stocks/stocks/entity"
	mock "github.com/stretchr/testify/mock"
)

// StockRepository is an autogenerated mock type for the StockRepository type
type StockRepository struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: id
func (_m *StockRepository) DeleteByID(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *StockRepository) FindAll() []entity.Stock {
	ret := _m.Called()

	var r0 []entity.Stock
	if rf, ok := ret.Get(0).(func() []entity.Stock); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Stock)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *StockRepository) GetByID(id string) (entity.Stock, error) {
	ret := _m.Called(id)

	var r0 entity.Stock
	if rf, ok := ret.Get(0).(func(string) entity.Stock); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Stock)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: stock
func (_m *StockRepository) Save(stock entity.Stock) entity.Stock {
	ret := _m.Called(stock)

	var r0 entity.Stock
	if rf, ok := ret.Get(0).(func(entity.Stock) entity.Stock); ok {
		r0 = rf(stock)
	} else {
		r0 = ret.Get(0).(entity.Stock)
	}

	return r0
}
